### ISSUE TITLE
how to fix the character encoding issue?

### ISSUE THREAD

**Issue by luckypoem** [dmjio/dmjio#1]
hi.
as per ur repo,i setup a blog: http://di.bright.biz.st/ ,but there is chinese character encoding issue,
how to fix it?
TKS

**Comment by dmjio** [comment]
Above this line https://github.com/dmjio/dmjio/blob/master/templates/default.html#L5, add the following:
```html
<meta charset="utf-8">
```
Or if you'd like to submit a PR with that addition, I would accept it.

**Comment by dmjio** [comment]
You could even make the PR from the GitHub UI if you wanted.

**Comment by luckypoem** [comment]
now it's ok.
i want to add my site url's superlink above dmj.io in the left area. which file to modify?
TKS

**Comment by dmjio** [comment]
Are you familiar with HTML?
